### PR TITLE
Fix spelling of Databases

### PR DESCRIPTION
**Pull request by jspiewak**

### CODE REVIEW

**Comment by edgararuiz** [comment]
Deploy preview for *rstudio-db* ready!

Built with commit f29cbfc3455039fb4a89c7b4484225c4df48c1da

https://deploy-preview-76--rstudio-db.netlify.com

**Comment by edgararuiz** [comment]
Thanks Josh!

**Comment by jspiewak** [comment]
What transforms the .Rmd to the .html?

**Comment by edgararuiz** [comment]
I have it pointing to the `public` folder, so I need to render it and republish, I'll do that today.

**Comment by jspiewak** [comment]
Still incorrect on the live site.

**Comment by edgararuiz** [comment]
Thanks for the ping, I'll check this afternoon

**Comment by edgararuiz** [comment]
Done, thanks again for pinging me: https://github.com/rstudio/db.rstudio.com/commit/425ea6ef3f4b3815841f6be58eaa0840dd5d335d

**Pull request merged**
